modLoader = "javafml"
loaderVersion = "[40,)"
license = "All rights reserved"

[[mods]]
modId = "haproxy_support"
version = "${version}"
displayName = "HAProxy Support"

[[dependencies.haproxy_support]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.haproxy_support]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
